# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DualSliderExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'DualSlider', '0.0.7'
  # Pods for DualSliderExample

end
